### ISSUE TITLE
Enable fling gestures in SnappingSheetPhysics

### ISSUE THREAD

**Issue by fujidaiti** [fujidaiti/smooth_sheets#20]
Currently, SnappingSheetPhysics determines where to snap only based on the position of a pointer where a gesture event ends, ignoring the speed and the direction of the gesture.

**Comment by appinteractive** [comment]
After testing the examples (which are incredible by the way) this is a really important point that is missing. Currently, it's really janky when you swipe fast, especially when using more than two snap points.

Any milestone for this one?

**Comment by fujidaiti** [comment]
>Currently, it's really janky when you swipe fast, especially when using more than two snap points

Could you please post a screenshot or video of this? It could be helpful.

**Comment by appinteractive** [comment]
A screenshot is not enough, and even a video is hard to describe the issue due to lacking pointers. I will try to setup an example, but currently I'm on a project deadline which I have to first complete. 

I try to describe what I see (I thought it's not that important as you describe it already in the title)

- we have a sheet with three snap points (0.2, 0.6, 1.0 extend)
- when we swipe up with a larger velocity, the sheet ignores that velocity and just tweens to the nearest snapping point.

This (especially with three snap points) does not feel right, as the animation abruptly slows down when you release the finger while moving and might even snap back instead of flying to the next or even last snap point.

Hope that explanation helps a bit.
